# generate_client_certs.yml

- name: Create client key
  command: "openssl genrsa -out {{ tmp_pathname }}/key.pem 4096"

- name: Create client CSR 
  command: "openssl req -subj '/CN=client' -new -key {{ tmp_pathname }}/key.pem -out {{ tmp_pathname }}/client.csr"

- name: Define extfile
  set_fact:
    tmp_extfile: "{{ tmp_pathname }}/client_extfile"

- name: Create extfile
  file:
    state: touch
    path: "{{ tmp_pextfile }}"

- name: Add extendedKeyUsage to extfile
  lineinfile:
    dest: "{{ tmp_extfile }}"
    line: "extendedKeyUsage = clientAuth"

- name: Create the client certificate 
  command: >
      openssl x509 -req -days 365 -sha256 -in {{ tmp_pathname }}/client.csr -CA {{ tmp_pathname }}/ca.pem 
      -CAkey {{ tmp_pathname }}/ca-key.pem -CAcreateserial -out {{ tmp_pathname }}/cert.pem 
      -extfile {{ tmp_extfile }} -passin file:{{ tmp_passphrase }}

- name: Copy client certificates from VM to host
  synchronize: 
    src: "{{ tmp_pathname }}/{{ item }}" 
    dest: "{{ adb_client_certpath }}/{{ item }}"
    mode: pull
  with_items:
    - ca.pem
    - cert.pem
    - key.pem

