- name: Install oc client
  include: intall_client.yml 
  when: inventory_hostname == 'localhost'

- name: Create the ADB virtual machine
  include: create_adb.yml
  when: inventory_hostname == 'localhost'
 
- include: create_certs.yml
  when: inventory_hostname == 'openshift.adb'

- name: Show output
  debug:
    var: vagrantout
  when: inventory_hostname == 'openshift.adb'
