- name: Install vagrant plugins 
  command: vagrant plugin install vagrant-service-manager vagrant-sshfs landrush

- name: Download the OpenShift Vagrant file
  get_url: 
    url: https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-openshift-setup/Vagrantfile
    dest: "{{ playbook_dir }}/Vagrantfile"

- name: Start the Vagrant host
  shell: vagrant up 2>&1 | tee {{ playbook_dir }}/vagrant_up.out 
  register: vagrantout

- name: Show output
  debug:
    var: vagrantout
