- name: Install oc client
  include: install_client.yml 
  when: inventory_hostname == 'localhost'

- name: Create the ADB virtual machine
  include: create_adb.yml
  when: inventory_hostname == 'localhost'

- name: Grant admin to openshift-dev
  include: grant_admin.yml
  when: inventory_hostname == 'localhost'
 
- include: create_certs.yml
  when: inventory_hostname == 'openshift.adb'

- name: Get output
  command: "cat {{ playbook_dir }}/vagrant_up.out"
  register: vagrantout 
  when: inventory_hostname == 'openshift.adb'

- name: Show output
  debug:
    var: vagrantout.stdout
  when: inventory_hostname == 'openshift.adb'
